version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-demo
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
